version: 0.2

env:
  variables:
    SHELL: "/bin/bash"
phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install pipenv
      - apt-get update && apt-get -y install zip && apt-get clean
  pre_build:
    commands:
      - pipenv --python 3.3.6
      - pipenv install
      - mkdir -p build
      - VIRTUAL_ENV=$(pipenv --venv)
      - cp -r $VIRTUAL_ENV/lib/python3.3/site-packages/* build/
      - cp -r utils build/
      - cp -r pipeline_lambda build/
  build:
    commands:
      - echo "Package lambda"
      - cd build
      - zip -r pipeline_lambda.zip *


artifacts:
  files:
    - pipeline_lambda.zip
  discard-paths: yes
  base-directory: build
